# Generated by Django 4.2.23 on 2025-08-09 13:23

from django.db import migrations

def create_superuser(apps, schema_editor):
    from django.contrib.auth.models import User
    from django.conf import settings

    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='adminpass'
        )
class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote_ip_address_vote_question_vote_session_key_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
